//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthOps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Breaks
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> BreakTypeId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual BreakTypes BreakTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
