//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthOps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Choices()
        {
            this.ApplicantAnswers = new HashSet<ApplicantAnswers>();
        }
    
        public System.Guid ChoiceId { get; set; }
        public Nullable<System.Guid> QuestionId { get; set; }
        public string ChoiceLetter { get; set; }
        public string Choice { get; set; }
        public Nullable<bool> IsAnswer { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantAnswers> ApplicantAnswers { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
