//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthOps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyTimeRecords
    {
        public int Id { get; set; }
        public string ScheduleId { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> isAgentApproved { get; set; }
        public Nullable<bool> isAdminApproved { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users CreatedByUser { get; set; }
        public virtual Schedules Schedules { get; set; }
    }
}
