//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthOps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equivalents
    {
        public string Id { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> Equivalent { get; set; }
        public Nullable<int> Items { get; set; }
    }
}
