//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthOps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exams()
        {
            this.Applicants = new HashSet<Applicants>();
            this.Questions = new HashSet<Questions>();
            this.TypingSpeeds = new HashSet<TypingSpeeds>();
            this.Videos = new HashSet<Videos>();
        }
    
        public System.Guid ExamId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public string ExamName { get; set; }
        public Nullable<int> ExamType { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsFinish { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsRandom { get; set; }
        public Nullable<int> Percentage { get; set; }
        public Nullable<int> Items { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applicants> Applicants { get; set; }
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questions> Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypingSpeeds> TypingSpeeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Videos> Videos { get; set; }
    }
}
