//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthOps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public string Id { get; set; }
        public string ItemId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> DateReleased { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Users Users { get; set; }
    }
}
