//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthOps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaves
    {
        public int Id { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<bool> isAdminApproved { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> NumberOfDays { get; set; }
    
        public virtual LeaveTypes LeaveTypes { get; set; }
        public virtual Users Modified_Users { get; set; }
        public virtual Users Users { get; set; }
    }
}
