//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthOps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questions()
        {
            this.ApplicantAnswers = new HashSet<ApplicantAnswers>();
            this.Choices = new HashSet<Choices>();
        }
    
        public System.Guid QuestionId { get; set; }
        public System.Guid ExamId { get; set; }
        public Nullable<System.Guid> VideoId { get; set; }
        public string Title { get; set; }
        public Nullable<int> Number { get; set; }
        public string Question { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantAnswers> ApplicantAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Choices> Choices { get; set; }
        public virtual Exams Exams { get; set; }
        public virtual Videos Videos { get; set; }
    }
}
