//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthOps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recordings
    {
        public int Id { get; set; }
        public string CampaignId { get; set; }
        public string UserId { get; set; }
        public byte[] Recording { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public string Errors { get; set; }
        public string CallerNumber { get; set; }
        public Nullable<int> ErrorTypeId { get; set; }
        public Nullable<System.DateTime> ErrorDateTime { get; set; }
        public string RootCauseAnalysis { get; set; }
        public string Commitment { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> AcknowledgmentDate { get; set; }
        public Nullable<System.DateTime> CoachingDate { get; set; }
    
        public virtual Campaigns Campaigns { get; set; }
        public virtual Users Users { get; set; }
        public virtual ErrorTypes ErrorTypes { get; set; }
        public virtual Users CreatedByUser { get; set; }
    }
}
