//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthOps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violations
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Violation { get; set; }
        public string ViolationTypeId { get; set; }
        public string RootCauseAnalysis { get; set; }
        public string Commitment { get; set; }
        public System.DateTime ViolationDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> AcknowledgmentDate { get; set; }
        public Nullable<bool> isAgentAcknowledge { get; set; }
        public Nullable<bool> isAdministratorAcknowledge { get; set; }
        public string AcknowledgeToken { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ViolationTypes ViolationTypes { get; set; }
    }
}
