//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthOps.Ops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public System.Guid ApplicantId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.Guid> ExamId { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<System.DateTime> DateTimeTaken { get; set; }
        public Nullable<bool> IsTaken { get; set; }
    
        public virtual User User { get; set; }
        public virtual Exam Exam { get; set; }
    }
}
