//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthOps.Ops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantAnswer
    {
        public System.Guid ApplicantAnswerId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.Guid> QuestionId { get; set; }
        public Nullable<System.Guid> ChoiceId { get; set; }
    
        public virtual Choice Choice { get; set; }
        public virtual User User { get; set; }
        public virtual Question Question { get; set; }
    }
}
