//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthOps.Ops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Choice()
        {
            this.ApplicantAnswers = new HashSet<ApplicantAnswer>();
        }
    
        public System.Guid ChoiceId { get; set; }
        public Nullable<System.Guid> QuestionId { get; set; }
        public string Choice1 { get; set; }
        public Nullable<bool> IsAnswer { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ChoiceLetter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantAnswer> ApplicantAnswers { get; set; }
        public virtual Question Question { get; set; }
    }
}
