//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthOps.Ops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalityResult
    {
        public System.Guid PersonalityResultId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> E { get; set; }
        public Nullable<int> I { get; set; }
        public Nullable<int> S { get; set; }
        public Nullable<int> N { get; set; }
        public Nullable<int> T { get; set; }
        public Nullable<int> F { get; set; }
        public Nullable<int> J { get; set; }
        public Nullable<int> P { get; set; }
        public Nullable<System.DateTime> DateTaken { get; set; }
    
        public virtual User User { get; set; }
    }
}
